name: swagger_ui
request:
  method: GET
  path:
    - /swagger/index.html
    - /swagger-ui.html
    - /v2/api-docs
    - /api-doc
    - /v2/swagger.json
    - /v1/swagger.json
    - /api/swagger.json
  headers: 
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
    Referer: http://www.baidu.com/
    Accept-Language: en
  timeout: 3
  allow_redirects: true
filter_expr: aw.lang == "java" || aw.lang == ""
verify_expr: response.body.bcontains(b"swagger-ui/css") || response.body.bcontains(b"{\"swagger\":\"2.0\"")